BG_COLOR = (0, 0, 0)

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
FPS = 60

RESOURCES_PATH = 'res/'
IMAGE_PATH = RESOURCES_PATH + 'img/'
AUDIO_PATH = RESOURCES_PATH + 'aud/'

# Game & grid
CELL_PX_WIDTH = 34
CELL_PX_HEIGHT = 34
GRID_WIDTH = 15
GRID_HEIGHT = 10
