BG_COLOR = (150,150,150)

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
FPS = 60

RESOURCES_PATH = 'res/'
IMAGE_PATH = RESOURCES_PATH + 'img/'
AUDIO_PATH = RESOURCES_PATH + 'aud/'
FONT_PATH = RESOURCES_PATH + 'font/'

# Game & grid
CELL_PX_WIDTH = 34
CELL_PX_HEIGHT = 34
GRID_WIDTH = 20
GRID_HEIGHT = 20
GRID_MINES = 80

WINDOW_PADDING = 10
UI_SPACE = 50

UI_COLOR = (0,0,0)
